USSAccordion0=new us.USSCreateAccordion(0) 
USSAccordion0=us.USSAppendAccordionHeader(USSAccordion0 ,'parent0' ) 
USSAccordion1=new us.USSCreateAccordion(1) 
USSAccordion1=us.USSAppendAccordionHeader(USSAccordion1 ,'Schema0' ) 
USSAccordion2=new us.USSCreateAccordion(2) 
USSAccordion2=us.USSAppendAccordionHeader(USSAccordion2 ,'personalInfo' ) 
USSTable=new us.USSCreateTable_();

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='name';
USSField.label='name';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='VARCHAR';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='20';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [1].dataType =  <NUMBER>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='Age';
USSField.label='Age';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='NUMBER';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='1';
USSField.max='3';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [2].dataType =  <NUMBER>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='Mobile';
USSField.label='MobileNo';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='NUMBER';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='1';
USSField.max='3';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [3].dataType =  <DATE>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='DOB';
USSField.label='Date of Birth';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='DATE';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='60';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [4].dataType =  <LIST>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='FUNCTION';
USSField.label='FUNCTION';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='LIST';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='60';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
USSAccordion2=new us.USSAppendAccordionSection(USSAccordion2,USSTable ) ; 
<!--### end container-->
// USSAccordion2=new us.USSAppendAccordionExapnd(USSAccordion2 ) ; 
<!--### FG1.2.L#.M#.001.003.003 rec[1] parent[0].dataType == 'XMLCONTAINER', actual  XMLCONTAINER-->
USSTable=new us.USSCreateTable_(); 
USSAccordion2=us.USSAppendAccordionHeader(USSAccordion2 ,'personalInfo' ) 
<!--### recSch [0].dataType =  <VARCHAR>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='name';
USSField.label='name';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='VARCHAR';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='20';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [1].dataType =  <NUMBER>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='Age';
USSField.label='Age';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='NUMBER';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='1';
USSField.max='3';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [2].dataType =  <NUMBER>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='Mobile';
USSField.label='MobileNo';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='NUMBER';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='1';
USSField.max='3';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [3].dataType =  <DATE>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='DOB';
USSField.label='Date of Birth';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='DATE';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='60';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [4].dataType =  <LIST>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='FUNCTION';
USSField.label='FUNCTION';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='LIST';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='60';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
USSAccordion2=new us.USSAppendAccordionSection(USSAccordion2,USSTable ) ; 
<!--### end container-->
//USSAccordion2=new us.USSAppendAccordionExapnd(USSAccordion2 ) ; 
<!--### FG1.2.L#.M#.001.003.003 rec[2] parent[0].dataType == 'XMLCONTAINER', actual  XMLCONTAINER-->
USSTable=new us.USSCreateTable_(); 
USSAccordion2=us.USSAppendAccordionHeader(USSAccordion2 ,'personalInfo' ) 
<!--### recSch [0].dataType =  <VARCHAR>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='name';
USSField.label='name';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='VARCHAR';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='20';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [1].dataType =  <NUMBER>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='Age';
USSField.label='Age';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='NUMBER';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='1';
USSField.max='3';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [2].dataType =  <NUMBER>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='Mobile';
USSField.label='MobileNo';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='NUMBER';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='1';
USSField.max='3';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [3].dataType =  <DATE>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='DOB';
USSField.label='Date of Birth';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='DATE';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='60';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);
USSTable=us.USSAppendTableRow(USSTableRow,USSTable); 
<!--### recSch [4].dataType =  <LIST>-->
<!--###  A:001 : Call frameField ..-->

USSTableRow = us.USSCreateTableRow_();	
USSField    = new us.USSField_(); 
USSField.group='uss';
USSField.name='FUNCTION';
USSField.label='FUNCTION';
USSField.task='NONE';
USSField.desc='';
USSField.htmlType='VARCHAR';
USSField.entitle='READONLY';
USSField.enttlname='';
USSField.mndf='N';
USSField.dataType='LIST';
USSField.cclass='ctable';
USSField.validate='';
USSField.dflt='';
USSField.min='0';
USSField.max='60';
USSField.tips='';
USSField.onkeyup='onKeyUp(this);';
USSField.onchange='onChange(this);';
USSField.onkeydown='onKeyDown(this);';
USSField.onkeypress='onKeyPress(this);';
USSField.onclick='onClick(this);';
USSField.listVal='||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY';
USSField.help='N';
USSField.helpLink='helpload';
USSField.xml='N';
USSField.Xpath='/';
USSTableRow=us.CreateField(USSField,USSTableRow);

USSAccordion2=new us.USSAppendAccordionSection(USSAccordion2,USSTable ) ; 
<!--### end container-->
USSAccordion2=new us.USSAppendAccordionExapnd(USSAccordion2 ) ; 

<!--###  Retuen F:002: frameGeneration ..-->
USSAccordion1=new us.USSAppendAccordionSection(USSAccordion1,USSAccordion2 ) ; 
<!--### end container-->
USSAccordion1=new us.USSAppendAccordionExapnd(USSAccordion1 ) ; 


USSAccordion0=new us.USSAppendAccordionSection(USSAccordion0,USSAccordion1 ) ; 
USSAccordion0=new us.USSAppendAccordionExapnd(USSAccordion0 ) ; 
